import { User } from "@/types/user";

export const mockUser: User = {
  id: "1",
  name: "ESAIE GUERSON LARA",
  email: "educa@gmail.com",
  role: "ADMIN",
};

export const mockSchool = {
  name: "Lycée Jacques Roumain",
  city: "Port-au-Prince",
};

export const mockStats = {
  totalEleves: { value: 452, variation: -5.6 },
  totalClasses: { value: 32, variation: 4.8 },
  totalUtilisateurs: { value: 510, variation: null },
  totalEvaluations: { value: 18, variation: null },
};

// ===== DONNÉES ENSEIGNANT =====
export const mockTeacherStats = {
  totalClasses: { value: 5, variation: 0 },
  totalStudents: { value: 127, variation: 3.2 },
  pendingEvaluations: { value: 12, variation: null },
  participationRate: { value: 94, variation: 2.1 },
};

export const mockTeacherCourses = [
  {
    id: "1",
    name: "Mathématiques",
    level: "NS3",
    year: "2023-2024",
    students: 32,
    color: "#013486", // Bleu
    image: "/cours/Math.jpg",
    nextClass: "Lundi 8h00",
    completionRate: 87,
    nextTopic: "Équations du second degré",
  },
  {
    id: "2",
    name: "Français",
    level: "NS2",
    year: "2023-2024",
    students: 30,
    color: "#F35403", // Orange
    image: "/cours/Francais.jpg",
    nextClass: "Mardi 10h00",
    completionRate: 92,
    nextTopic: "La conjugaison au passé simple",
  },
  {
    id: "3",
    name: "SVT Biologie",
    level: "NS3",
    year: "2023-2024",
    students: 28,
    color: "#43a047", // Vert
    image: "/cours/Biologie.jpg",
    nextClass: "Mercredi 14h00",
    completionRate: 78,
    nextTopic: "La photosynthèse",
  },
  {
    id: "4",
    name: "Histoire-Géo",
    level: "NS1",
    year: "2023-2024",
    students: 25,
    color: "#d32f2f", // Rouge
    image: "/cours/Histoire.jpg",
    nextClass: "Jeudi 9h00",
    completionRate: 85,
    nextTopic: "La révolution haïtienne",
  },
  {
    id: "5",
    name: "Informatique",
    level: "NS2",
    year: "2023-2024",
    students: 24,
    color: "#7c3aed", // Violet
    image: "/cours/Informatique.jpg",
    nextClass: "Vendredi 11h00",
    completionRate: 95,
    nextTopic: "Algorithmique avancée",
  },
  {
    id: "6",
    name: "Géographie",
    level: "NS3",
    year: "2023-2024",
    students: 29,
    color: "#00897b", // Teal
    image: "/cours/Geographie.jpg",
    nextClass: "Lundi 14h00",
    completionRate: 88,
    nextTopic: "Les climats du monde",
  },
  {
    id: "7",
    name: "Physique",
    level: "NS2",
    year: "2023-2024",
    students: 26,
    color: "#5e35b1", // Deep Purple
    image: "/cours/Math.jpg",
    nextClass: "Mardi 8h00",
    completionRate: 82,
    nextTopic: "Les lois de Newton",
  },
  {
    id: "8",
    name: "Chimie",
    level: "NS3",
    year: "2023-2024",
    students: 27,
    color: "#e53935", // Red
    image: "/cours/Biologie.jpg",
    nextClass: "Mercredi 10h00",
    completionRate: 79,
    nextTopic: "Réactions chimiques",
  },
  {
    id: "9",
    name: "Anglais",
    level: "NS1",
    year: "2023-2024",
    students: 31,
    color: "#1e88e5", // Blue
    image: "/cours/Francais.jpg",
    nextClass: "Jeudi 11h00",
    completionRate: 91,
    nextTopic: "Present perfect tense",
  },
  {
    id: "10",
    name: "Espagnol",
    level: "NS2",
    year: "2023-2024",
    students: 22,
    color: "#f4511e", // Deep Orange
    image: "/cours/Francais.jpg",
    nextClass: "Vendredi 14h00",
    completionRate: 86,
    nextTopic: "Los verbos irregulares",
  },
  {
    id: "11",
    name: "Éducation Physique",
    level: "NS3",
    year: "2023-2024",
    students: 35,
    color: "#43a047", // Green
    image: "/cours/Histoire.jpg",
    nextClass: "Lundi 15h00",
    completionRate: 94,
    nextTopic: "Basketball",
  },
  {
    id: "12",
    name: "Arts Plastiques",
    level: "NS1",
    year: "2023-2024",
    students: 20,
    color: "#e91e63", // Pink
    image: "/cours/Informatique.jpg",
    nextClass: "Mardi 15h00",
    completionRate: 97,
    nextTopic: "Peinture abstraite",
  },
];

export const mockTeacherStudents = [
  {
    id: "1",
    name: "Marie-Claire Joseph",
    email: "marie.joseph@educa.ht",
    phone: "+509 3712-8945",
    class: "NS3",
    photo: "/images/student1.jpg",
    performance: 87,
    average: 87,
    attendance: 95,
    lastGrade: 85,
    trend: "stable", // up, down, stable
    subjects: [
      { name: "Mathématiques", grade: 85, max: 100 },
      { name: "Français", grade: 90, max: 100 },
      { name: "SVT", grade: 87, max: 100 },
    ],
  },
  {
    id: "2",
    name: "Jean-Baptiste Pierre",
    email: "jean.pierre@educa.ht",
    phone: "+509 4523-1267",
    class: "NS2",
    photo: "/images/student2.jpg",
    performance: 92,
    average: 92,
    attendance: 98,
    lastGrade: 95,
    trend: "up",
    subjects: [
      { name: "Mathématiques", grade: 95, max: 100 },
      { name: "Français", grade: 90, max: 100 },
      { name: "SVT", grade: 91, max: 100 },
    ],
  },
  {
    id: "3",
    name: "Sophia Delva",
    email: "sophia.delva@educa.ht",
    phone: "+509 3891-2345",
    class: "NS3",
    photo: "/images/student3.jpg",
    performance: 78,
    average: 78,
    attendance: 88,
    lastGrade: 72,
    trend: "down",
    subjects: [
      { name: "Mathématiques", grade: 75, max: 100 },
      { name: "Français", grade: 80, max: 100 },
      { name: "SVT", grade: 79, max: 100 },
    ],
  },
  {
    id: "4",
    name: "Marcus Laurent",
    email: "marcus.laurent@educa.ht",
    phone: "+509 4712-9876",
    class: "NS1",
    photo: "/images/student4.jpg",
    performance: 85,
    average: 85,
    attendance: 92,
    lastGrade: 88,
    trend: "up",
    subjects: [
      { name: "Mathématiques", grade: 88, max: 100 },
      { name: "Français", grade: 83, max: 100 },
      { name: "SVT", grade: 84, max: 100 },
    ],
  },
  {
    id: "5",
    name: "Nathalie Augustin",
    email: "nathalie.augustin@educa.ht",
    phone: "+509 3654-7890",
    class: "NS2",
    photo: "/images/student5.jpg",
    performance: 95,
    average: 95,
    attendance: 100,
    lastGrade: 97,
    trend: "stable",
    subjects: [
      { name: "Mathématiques", grade: 97, max: 100 },
      { name: "Français", grade: 94, max: 100 },
      { name: "SVT", grade: 94, max: 100 },
    ],
  },
  {
    id: "6",
    name: "Alex Duval",
    email: "alex.duval@educa.ht",
    phone: "+509 3765-4321",
    class: "NS3",
    photo: "/images/student6.jpg",
    performance: 68,
    average: 68,
    attendance: 75,
    lastGrade: 65,
    trend: "down",
    subjects: [
      { name: "Mathématiques", grade: 65, max: 100 },
      { name: "Français", grade: 70, max: 100 },
      { name: "SVT", grade: 69, max: 100 },
    ],
  },
  {
    id: "7",
    name: "Isabelle Martin",
    email: "isabelle.martin@educa.ht",
    phone: "+509 4987-6543",
    class: "NS1",
    photo: "/images/student7.jpg",
    performance: 91,
    average: 91,
    attendance: 96,
    lastGrade: 93,
    trend: "up",
    subjects: [
      { name: "Mathématiques", grade: 93, max: 100 },
      { name: "Français", grade: 90, max: 100 },
      { name: "SVT", grade: 90, max: 100 },
    ],
  },
  {
    id: "8",
    name: "Thomas Beaufort",
    email: "thomas.beaufort@educa.ht",
    phone: "+509 3821-9876",
    class: "NS2",
    photo: "/images/student8.jpg",
    performance: 82,
    average: 82,
    attendance: 90,
    lastGrade: 80,
    trend: "stable",
    subjects: [
      { name: "Mathématiques", grade: 80, max: 100 },
      { name: "Français", grade: 85, max: 100 },
      { name: "SVT", grade: 81, max: 100 },
    ],
  },
];

export const mockAnnouncements = [
  {
    id: "1",
    title: "Réunion pédagogique",
    content: "Réunion obligatoire pour tous les enseignants ce vendredi à 15h00",
    date: "2024-02-15",
    priority: "high",
  },
  {
    id: "2",
    title: "Examens de mi-session",
    content: "Les examens de mi-session débutent la semaine prochaine. Préparez vos copies.",
    date: "2024-02-18",
    priority: "medium",
  },
  {
    id: "3",
    title: "Nouvelle plateforme éducative",
    content: "Formation sur la nouvelle plateforme d'apprentissage en ligne ce mardi.",
    date: "2024-02-20",
    priority: "low",
  },
];

export const mockWeeklyPerformance = [
  { day: "Lun", rate: 92 },
  { day: "Mar", rate: 88 },
  { day: "Mer", rate: 95 },
  { day: "Jeu", rate: 87 },
  { day: "Ven", rate: 94 },
];

// ===== DONNÉES CLASSES ENSEIGNANT =====
export const mockTeacherClasses = [
  {
    id: "1",
    name: "NS3",
    fullName: "Nouvelle Secondaire 3",
    level: "Secondaire",
    year: "2024-2025",
    students: 32,
    room: "Salle B12",
    mainTeacher: "Prof. ESAIE GUERSON",
    color: "#7c3aed", // Violet - Secondaire
    attendance: 93,
    average: 76,
    studentsInDifficulty: 3,
    nextClass: "Lundi 10h00",
    pendingHomework: 4,
    nextExam: "Vendredi 15 Mars",
  },
  {
    id: "2",
    name: "NS2",
    fullName: "Nouvelle Secondaire 2",
    level: "Secondaire",
    year: "2024-2025",
    students: 28,
    room: "Salle A8",
    mainTeacher: "Prof. ESAIE GUERSON",
    color: "#7c3aed", // Violet - Secondaire
    attendance: 89,
    average: 72,
    studentsInDifficulty: 5,
    nextClass: "Mardi 14h00",
    pendingHomework: 2,
    nextExam: "Lundi 18 Mars",
  },
  {
    id: "3",
    name: "NS1",
    fullName: "Nouvelle Secondaire 1",
    level: "Secondaire",
    year: "2024-2025",
    students: 30,
    room: "Salle C5",
    mainTeacher: "Prof. ESAIE GUERSON",
    color: "#7c3aed", // Violet - Secondaire
    attendance: 95,
    average: 81,
    studentsInDifficulty: 2,
    nextClass: "Mercredi 8h00",
    pendingHomework: 6,
    nextExam: "Jeudi 20 Mars",
  },
  {
    id: "4",
    name: "6ème AF",
    fullName: "6ème Année Fondamentale",
    level: "Fondamental",
    year: "2024-2025",
    students: 25,
    room: "Salle D3",
    mainTeacher: "Prof. Marie Joseph",
    color: "#013486", // Bleu - Fondamental
    attendance: 97,
    average: 85,
    studentsInDifficulty: 1,
    nextClass: "Jeudi 9h00",
    pendingHomework: 3,
    nextExam: "Vendredi 22 Mars",
  },
];
